// =====================================================================
// CS 3370 -- Programming Assignment 3: BigInt
// PERFORMANCE AND MEMORY HARNESS ("Performance and Memory Report")
// =====================================================================
//
// HOW TO USE IT
//   Include this header in your main.cpp and call one function:
//
//       #include "bigint.h"
//       #include "numeric.h"
//       #include "perf_bigint.h"
//
//       int main() {
//           // ... your own code ...
//           runPerformanceReport();
//       }
//
//   IMPORTANT: include this header in main.cpp ONLY -- never in
//   BigInt.cpp or in a second .cpp file. It defines the program's global
//   operator new and operator delete (see below), and a program may
//   define those only once. Including it twice gives a
//   "multiple definition of operator new" link error.
//
//   Build and run your program TWICE, and put both sets of numbers in
//   your report:
//       g++ -std=c++20 -Wall -Wextra -O0 main.cpp BigInt.cpp -o prog_O0
//       g++ -std=c++20 -Wall -Wextra -O2 main.cpp BigInt.cpp -o prog_O2
//   On OnlineGDB, put -O0 or -O2 in the "Extra Compiler Flags" box.
//
// WHAT IT DOES
//   Computes factorial<BigInt>(10000) with YOUR BigInt and YOUR
//   factorial template, checks that the answer is right (a fast wrong
//   answer is not a result), and then measures, over 3 timed runs:
//     * how long it takes (std::chrono::steady_clock),
//     * how many heap bytes the finished result holds,
//     * the peak extra heap usage while it was being computed, and
//     * how many heap allocations the computation made.
//
// HOW IT MEASURES MEMORY WITHOUT LOOKING INSIDE YOUR CLASS
//   It replaces the global operator new and operator delete -- the same
//   technique as memory.cpp in Module 2 -- and keeps a running count of
//   bytes currently allocated. Every std::vector, std::string, or other
//   container inside your BigInt gets its memory through these
//   functions, so the count sees it, including code in BigInt.cpp.
//
// WHAT IT CANNOT TELL YOU
//   It sees bytes, not your design. Your report must still state your
//   representation, your storage's element count and capacity() (print
//   those from inside your own code), and your estimate for another
//   representation.
//
//   Do not edit this file. It will be replaced with a fresh copy when
//   your program is graded.
// =====================================================================
#ifndef CS3370_PERF_BIGINT_H
#define CS3370_PERF_BIGINT_H

#include "bigint.h"
#include "numeric.h"

#include <chrono>
#include <cstddef>
#include <cstdlib>
#include <exception>
#include <iomanip>
#include <iostream>
#include <new>

// ---------------------------------------------------------------------
// Heap accounting.
// ---------------------------------------------------------------------
namespace cs3370_perf_detail {
inline std::size_t liveBytes   = 0;   // bytes currently allocated
inline std::size_t peakBytes   = 0;   // high-water mark of liveBytes
inline std::size_t allocations = 0;   // number of calls to operator new

// Each block carries a small header recording its requested size, so
// operator delete knows how many bytes are being returned.
struct alignas(std::max_align_t) BlockHeader {
    std::size_t size;
};
}  // namespace cs3370_perf_detail

// Replacement global allocation functions. These may NOT be declared
// inline (the language forbids it), which is why this header must be
// included in exactly one .cpp file.
void* operator new(std::size_t size) {
    namespace d = cs3370_perf_detail;
    void* raw = std::malloc(sizeof(d::BlockHeader) + size);
    if (raw == nullptr) throw std::bad_alloc{};
    d::BlockHeader* header = static_cast<d::BlockHeader*>(raw);
    header->size = size;
    d::liveBytes += size;
    if (d::liveBytes > d::peakBytes) d::peakBytes = d::liveBytes;
    ++d::allocations;
    return header + 1;
}

void operator delete(void* p) noexcept {
    namespace d = cs3370_perf_detail;
    if (p == nullptr) return;
    d::BlockHeader* header = static_cast<d::BlockHeader*>(p) - 1;
    d::liveBytes -= header->size;
    std::free(header);
}

void operator delete(void* p, std::size_t) noexcept { ::operator delete(p); }
void* operator new[](std::size_t size) { return ::operator new(size); }
void operator delete[](void* p) noexcept { ::operator delete(p); }
void operator delete[](void* p, std::size_t) noexcept { ::operator delete(p); }

// ---------------------------------------------------------------------
namespace cs3370_perf_detail {

inline constexpr unsigned    kN              = 10000;
inline constexpr std::size_t kExpectedDigits = 35660;
inline constexpr std::size_t kExpectedZeros  = 2499;
inline constexpr int         kTrials         = 3;

inline std::size_t trailingZeros(const BigInt& b) {
    std::size_t count = 0;
    while (count < b.digitCount() && b[count] == 0)
        ++count;
    return count;
}

inline void printBuildInfo() {
    std::cout << "Build information\n";
#if defined(__clang__)
    std::cout << "  compiler:       clang " << __clang_version__ << '\n';
#elif defined(__GNUC__)
    std::cout << "  compiler:       g++ " << __VERSION__ << '\n';
#elif defined(_MSC_VER)
    std::cout << "  compiler:       MSVC " << _MSC_VER << '\n';
#else
    std::cout << "  compiler:       (unknown)\n";
#endif
    std::cout << "  __cplusplus:    " << __cplusplus << '\n';
#if defined(__OPTIMIZE__)
    std::cout << "  optimization:   ON  (built with -O1 or higher)\n";
#else
    std::cout << "  optimization:   OFF (built with -O0)\n";
#endif
    std::cout << "  sizeof(BigInt): " << sizeof(BigInt)
              << " bytes (the object itself, not counting its heap data)\n\n";
}

struct Trial {
    double      ms;
    std::size_t heldBytes;     // heap bytes still owned by the result
    std::size_t peakExtra;     // peak heap above the starting level
    std::size_t allocations;   // calls to operator new during the run
};

}  // namespace cs3370_perf_detail

// =====================================================================
// The one function you call. Returns 0 on success, 1 if the result of
// 10000! was wrong or an exception was thrown.
// =====================================================================
inline int runPerformanceReport() {
    namespace d = cs3370_perf_detail;

    std::cout << "\nCS 3370 Program 3 -- BigInt performance and memory report\n"
              << "Computing factorial<BigInt>(" << d::kN << ")\n\n";
    d::printBuildInfo();

    try {
        // --- correctness gate ------------------------------------------
        {
            BigInt check = factorial<BigInt>(d::kN);
            const std::size_t digits = check.digitCount();
            const std::size_t zeros  = d::trailingZeros(check);
            const bool digitsOk = digits == d::kExpectedDigits;
            const bool zerosOk  = zeros == d::kExpectedZeros;
            std::cout << "Correctness\n"
                      << "  digit count:    " << digits
                      << (digitsOk ? "  (correct)" : "  (WRONG -- expected 35660)") << '\n'
                      << "  trailing zeros: " << zeros
                      << (zerosOk ? "  (correct)" : "  (WRONG -- expected 2499)") << "\n\n";
            if (!digitsOk || !zerosOk) {
                std::cout << "The result is wrong, so timing it would be meaningless.\n"
                          << "Fix the failing required checks first.\n";
                return 1;
            }
        }

        // --- timed trials -----------------------------------------------
        d::Trial trials[d::kTrials];
        for (d::Trial& t : trials) {
            const std::size_t startLive   = d::liveBytes;
            const std::size_t startAllocs = d::allocations;
            d::peakBytes = d::liveBytes;

            auto start = std::chrono::steady_clock::now();
            BigInt result = factorial<BigInt>(d::kN);
            auto stop = std::chrono::steady_clock::now();

            t.ms          = std::chrono::duration<double, std::milli>(stop - start).count();
            t.heldBytes   = d::liveBytes - startLive;
            t.peakExtra   = d::peakBytes - startLive;
            t.allocations = d::allocations - startAllocs;
            // `result` is destroyed here, returning its memory before the next run
        }

        // Save and restore the stream's formatting so your later output
        // is not affected.
        const std::ios_base::fmtflags oldFlags = std::cout.flags();
        const std::streamsize oldPrecision = std::cout.precision();

        std::cout << "Timed runs\n"
                  << "  run    time (ms)    result holds (bytes)    peak extra (bytes)    allocations\n";
        double best = trials[0].ms;
        for (int i = 0; i < d::kTrials; ++i) {
            const d::Trial& t = trials[i];
            if (t.ms < best) best = t.ms;
            std::cout << std::right << "  " << std::setw(3) << i + 1
                      << std::setw(13) << std::fixed << std::setprecision(2) << t.ms
                      << std::setw(24) << t.heldBytes
                      << std::setw(22) << t.peakExtra
                      << std::setw(15) << t.allocations << '\n';
        }

        const double bytesPerDigit =
            static_cast<double>(trials[0].heldBytes) / d::kExpectedDigits;
        std::cout << "\nSummary\n"
                  << "  best time:               " << std::setprecision(2) << best << " ms\n"
                  << "  heap held by the result: " << trials[0].heldBytes << " bytes"
                  << "  (" << std::setprecision(3) << bytesPerDigit
                  << " bytes per decimal digit)\n\n"
                  << "Still to put in your report yourself:\n"
                  << "  1. your representation (element type and base), and why\n"
                  << "  2. these numbers for BOTH -O0 and -O2\n"
                  << "  3. your storage's element count and capacity(), printed from your\n"
                  << "     own code -- check that capacity() x element size matches the\n"
                  << "     'result holds' number above\n"
                  << "  4. your estimate for another representation\n";

        std::cout.flags(oldFlags);
        std::cout.precision(oldPrecision);
    } catch (const std::exception& e) {
        std::cout << "Exception while computing " << d::kN << "!: " << e.what() << '\n';
        return 1;
    }
    return 0;
}

#endif  // CS3370_PERF_BIGINT_H
