// =====================================================================
// CS 3370 -- Programming Assignment 3: BigInt
// TEST HARNESS for "Required Output" (checks 1-13)
// =====================================================================
//
// HOW TO USE IT
//   Include this header in your main.cpp and call one function:
//
//       #include "bigint.h"
//       #include "numeric.h"
//       #include "test_bigint.h"
//
//       int main() {
//           // ... your own code ...
//           runRequiredChecks();            // run all 13 checks
//       }
//
//   To run only some checks, list their numbers:
//
//           runRequiredChecks({7, 12});     // only checks 7 and 12
//
//   Running checks one at a time is useful if your program CRASHES:
//   a segmentation fault cannot be caught, so it ends the whole run.
//
//   runRequiredChecks() returns the number of failed checks (0 means
//   everything passed), so you can end main with
//       return runRequiredChecks() == 0 ? 0 : 1;
//
// WHAT IT DOES
//   Runs every check from the "Required Output" table against YOUR
//   BigInt and YOUR templates, and prints PASS or FAIL for each one,
//   with what it expected and what it got. It uses only the public
//   interface in bigint.h and the templates in numeric.h -- it never
//   looks inside your class. An exception thrown by your code fails
//   that one check; the remaining checks still run.
//
// NOTES
//   * Check 6 confirms the ANSWER (F(4782) is the first Fibonacci
//     number with 1,000 digits). How you SEARCH for it is still yours
//     to write in main.cpp.
//   * Check 13 reports your concept at run time so that a wrong concept
//     does not stop everything else from compiling. Your main.cpp must
//     still contain the four static_assert lines from the handout.
//   * Do not edit this file. It will be replaced with a fresh copy when
//     your program is graded.
// =====================================================================
#ifndef CS3370_TEST_BIGINT_H
#define CS3370_TEST_BIGINT_H

#include "bigint.hpp"
#include "numeric.hpp"

#include <concepts>
#include <exception>
#include <initializer_list>
#include <iomanip>
#include <iostream>
#include <limits>
#include <set>
#include <stdexcept>
#include <string>

namespace cs3370_test_detail {

// ---------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------
struct Reporter {
    int passed = 0;
    int failed = 0;

    void operator()(const std::string& id, const std::string& what, bool ok,
                    const std::string& expected = "true",
                    const std::string& got = "false") {
        (ok ? passed : failed) += 1;
        std::cout << (ok ? "  [PASS] " : "  [FAIL] ")
                  << std::left << std::setw(5) << id << what << '\n';
        if (!ok) {
            std::cout << "           expected: " << expected << '\n'
                      << "           got:      " << got << '\n';
        }
    }
};

inline void heading(int n, const std::string& title) {
    std::cout << "\n=== Check " << n << ": " << title << " ===\n";
}

inline std::string yesNo(bool b) { return b ? "true" : "false"; }

// ---------------------------------------------------------------------
// Small helpers built ONLY from BigInt's public interface.
// ---------------------------------------------------------------------
inline long long digitSum(const BigInt& b) {
    long long sum = 0;
    for (std::size_t i = 0; i < b.digitCount(); ++i)
        sum += b[i];
    return sum;
}

inline std::size_t trailingZeros(const BigInt& b) {
    std::size_t count = 0;
    while (count < b.digitCount() && b[count] == 0)
        ++count;
    return count;
}

// operator[], digitCount(), and toString() must all agree.
inline bool digitsAgreeWithString(const BigInt& b) {
    std::string s = b.toString();
    if (!s.empty() && s[0] == '-') s.erase(0, 1);
    if (s.size() != b.digitCount()) return false;
    for (std::size_t i = 0; i < s.size(); ++i)
        if (b[i] != s[s.size() - 1 - i] - '0') return false;
    return true;
}

// ---------------------------------------------------------------------
// Expected data for check 1 (true n! and the 64-bit wrapped value).
// ---------------------------------------------------------------------
struct FactRow {
    unsigned n;
    const char* exact;
    unsigned long long wrapped;
};

inline constexpr FactRow kFactorials[] = {
    {1, "1", 1ULL},
    {2, "2", 2ULL},
    {3, "6", 6ULL},
    {4, "24", 24ULL},
    {5, "120", 120ULL},
    {6, "720", 720ULL},
    {7, "5040", 5040ULL},
    {8, "40320", 40320ULL},
    {9, "362880", 362880ULL},
    {10, "3628800", 3628800ULL},
    {11, "39916800", 39916800ULL},
    {12, "479001600", 479001600ULL},
    {13, "6227020800", 6227020800ULL},
    {14, "87178291200", 87178291200ULL},
    {15, "1307674368000", 1307674368000ULL},
    {16, "20922789888000", 20922789888000ULL},
    {17, "355687428096000", 355687428096000ULL},
    {18, "6402373705728000", 6402373705728000ULL},
    {19, "121645100408832000", 121645100408832000ULL},
    {20, "2432902008176640000", 2432902008176640000ULL},
    {21, "51090942171709440000", 14197454024290336768ULL},
    {22, "1124000727777607680000", 17196083355034583040ULL},
    {23, "25852016738884976640000", 8128291617894825984ULL},
    {24, "620448401733239439360000", 10611558092380307456ULL},
    {25, "15511210043330985984000000", 7034535277573963776ULL},
};

// =====================================================================
// The checks
// =====================================================================

inline void check1(Reporter& report) {
    heading(1, "factorial<unsigned long long> vs factorial<BigInt>, n = 1..25");
    std::cout << "   n  " << std::left << std::setw(22) << "unsigned long long"
              << "  BigInt\n";

    bool ullOk = true, bigOk = true;
    unsigned firstDiff = 0;
    for (const FactRow& row : kFactorials) {
        unsigned long long u = factorial<unsigned long long>(row.n);
        std::string b = factorial<BigInt>(row.n).toString();
        bool differ = std::to_string(u) != b;
        if (differ && firstDiff == 0) firstDiff = row.n;
        if (u != row.wrapped) ullOk = false;
        if (b != row.exact) bigOk = false;
        std::cout << "  " << std::right << std::setw(2) << row.n << "  "
                  << std::left << std::setw(22) << u << "  " << b
                  << (differ ? "   <-- differ" : "") << '\n';
    }
    report("1a", "factorial<unsigned long long> matches expected values", ullOk);
    report("1b", "factorial<BigInt> matches exact n! for n = 1..25", bigOk);
    report("1c", "first n where the two differ", firstDiff == 21,
           "21", firstDiff == 0 ? "(none)" : std::to_string(firstDiff));
}

inline void check2(Reporter& report) {
    heading(2, "100!");
    BigInt f = factorial<BigInt>(100);
    report("2a", "digit count", f.digitCount() == 158,
           "158", std::to_string(f.digitCount()));
    report("2b", "digit sum (via operator[])", digitSum(f) == 648,
           "648", std::to_string(digitSum(f)));
    report("2c", "trailing zeros (via operator[])", trailingZeros(f) == 24,
           "24", std::to_string(trailingZeros(f)));
    report("2d", "operator[], digitCount() and toString() agree",
           digitsAgreeWithString(f));
}

inline void check3(Reporter& report) {
    heading(3, "1000!");
    BigInt f = factorial<BigInt>(1000);
    report("3a", "digit count", f.digitCount() == 2568,
           "2568", std::to_string(f.digitCount()));
    report("3b", "trailing zeros", trailingZeros(f) == 249,
           "249", std::to_string(trailingZeros(f)));
    report("3c", "operator[], digitCount() and toString() agree",
           digitsAgreeWithString(f));
}

inline void check4(Reporter& report) {
    heading(4, "power<BigInt>(2, 64)");
    BigInt p = power<BigInt>(2, 64);
    report("4", "power<BigInt>(2, 64) == BigInt(\"18446744073709551616\")",
           p == BigInt(std::string("18446744073709551616")),
           "18446744073709551616", p.toString());
}

inline void check5(Reporter& report) {
    heading(5, "power<BigInt>(2, 1000)");
    BigInt p = power<BigInt>(2, 1000);
    report("5a", "digit count", p.digitCount() == 302,
           "302", std::to_string(p.digitCount()));
    report("5b", "digit sum", digitSum(p) == 1366,
           "1366", std::to_string(digitSum(p)));
}

inline void check6(Reporter& report) {
    heading(6, "first Fibonacci number with 1,000 digits");
    report("6a", "fibonacci<BigInt>(1) == 1 and fibonacci<BigInt>(2) == 1",
           fibonacci<BigInt>(1) == BigInt(1) && fibonacci<BigInt>(2) == BigInt(1));
    report("6b", "fibonacci<BigInt>(10) == 55",
           fibonacci<BigInt>(10) == BigInt(55),
           "55", fibonacci<BigInt>(10).toString());
    BigInt before = fibonacci<BigInt>(4781);
    BigInt at     = fibonacci<BigInt>(4782);
    report("6c", "F(4781) has 999 digits", before.digitCount() == 999,
           "999", std::to_string(before.digitCount()));
    report("6d", "F(4782) has 1000 digits", at.digitCount() == 1000,
           "1000", std::to_string(at.digitCount()));
}

inline void check7(Reporter& report) {
    heading(7, "most negative long long");
    BigInt m(std::numeric_limits<long long>::min());
    report("7a", "BigInt(LLONG_MIN).toString()",
           m.toString() == "-9223372036854775808",
           "-9223372036854775808", m.toString());
    report("7b", "BigInt(LLONG_MIN).isNegative()", m.isNegative());
    BigInt mx(std::numeric_limits<long long>::max());
    report("7c", "BigInt(LLONG_MAX).toString()",
           mx.toString() == "9223372036854775807",
           "9223372036854775807", mx.toString());
}

inline void check8(Reporter& report) {
    heading(8, "signs and zero");
    BigInt d = BigInt(5) - 12;
    report("8a", "BigInt(5) - 12", d.toString() == "-7", "-7", d.toString());

    BigInt negZero = -BigInt(0);
    report("8b", "-BigInt(0) prints 0", negZero.toString() == "0",
           "0", negZero.toString());
    report("8c", "-BigInt(0) is not negative", !negZero.isNegative(),
           "false", yesNo(negZero.isNegative()));

    BigInt z(std::string("-000"));
    report("8d", "BigInt(\"-000\") == 0", z == 0, "true", yesNo(z == 0));
    report("8e", "BigInt(\"-000\") prints 0", z.toString() == "0",
           "0", z.toString());
}

inline void check9(Reporter& report) {
    heading(9, "aliasing: a *= a, then a += a");
    BigInt a = 99999999999;
    a *= a;
    report("9a", "a *= a", a.toString() == "9999999999800000000001",
           "9999999999800000000001", a.toString());
    a += a;
    report("9b", "then a += a", a.toString() == "19999999999600000000002",
           "19999999999600000000002", a.toString());
}

inline void check10(Reporter& report) {
    heading(10, "prefix and postfix ++");
    BigInt b = 999999999;
    BigInt c = b++;
    BigInt d = ++b;
    report("10a", "b", b.toString() == "1000000001", "1000000001", b.toString());
    report("10b", "c = b++", c.toString() == "999999999", "999999999", c.toString());
    report("10c", "d = ++b", d.toString() == "1000000001", "1000000001", d.toString());
}

// Templates, so that a missing operator is reported as FAIL instead of
// stopping your whole program from compiling.
template <typename T>
concept IntOnLeft = requires(const T& b) { { 1 + b } -> std::convertible_to<T>; };
template <typename T>
concept IntOnRight = requires(const T& b) { { b + 1 } -> std::convertible_to<T>; };

template <typename T>
void check11Impl(Reporter& report) {
    report("11a", "1 + b compiles", IntOnLeft<T>);
    report("11b", "b + 1 compiles", IntOnRight<T>);
    if constexpr (IntOnLeft<T> && IntOnRight<T>) {
        T b(std::string("123456789012345678901234567890"));
        T left  = 1 + b;
        T right = b + 1;
        report("11c", "1 + b == b + 1", left == right,
               "true", left.toString() + " vs " + right.toString());
        report("11d", "value of b + 1",
               right.toString() == "123456789012345678901234567891",
               "123456789012345678901234567891", right.toString());
    }
}

inline void check11(Reporter& report) {
    heading(11, "1 + b and b + 1");
    check11Impl<BigInt>(report);
}

// Runs `action` and reports whether it threw exactly the expected type.
template <typename Expected, typename Action>
void expectThrow(Reporter& report, const std::string& id,
                 const std::string& what, Action action) {
    const std::string expectedName =
        std::same_as<Expected, std::invalid_argument> ? "std::invalid_argument"
                                                      : "std::out_of_range";
    try {
        action();
        report(id, what, false, expectedName, "no exception");
    } catch (const Expected&) {
        report(id, what, true, expectedName, expectedName);
    } catch (const std::exception& e) {
        report(id, what, false, expectedName,
               std::string("a different exception: ") + e.what());
    } catch (...) {
        report(id, what, false, expectedName, "a non-standard exception");
    }
}

inline void check12(Reporter& report) {
    heading(12, "error handling");
    expectThrow<std::invalid_argument>(report, "12a", "BigInt(\"12a3\") throws",
        [] { BigInt b(std::string("12a3")); (void)b; });
    expectThrow<std::invalid_argument>(report, "12b", "BigInt(\"\") throws",
        [] { BigInt b(std::string("")); (void)b; });
    expectThrow<std::invalid_argument>(report, "12c", "BigInt(\"-\") throws",
        [] { BigInt b(std::string("-")); (void)b; });
    expectThrow<std::out_of_range>(report, "12d", "factorial<BigInt>(100)[500] throws",
        [] { int d = factorial<BigInt>(100)[500]; (void)d; });
}

inline void check13(Reporter& report) {
    heading(13, "the NumberLike concept");
    constexpr bool i = NumberLike<int>;
    constexpr bool d = NumberLike<double>;
    constexpr bool b = NumberLike<BigInt>;
    constexpr bool s = NumberLike<std::string>;
    report("13a", "NumberLike<int>", i, "true", yesNo(i));
    report("13b", "NumberLike<double>", d, "true", yesNo(d));
    report("13c", "NumberLike<BigInt>", b, "true", yesNo(b));
    report("13d", "!NumberLike<std::string>", !s, "false", yesNo(s));
}

using CheckFn = void (*)(Reporter&);
inline constexpr CheckFn kChecks[] = {
    check1, check2, check3, check4, check5, check6, check7,
    check8, check9, check10, check11, check12, check13,
};
inline constexpr int kNumChecks = sizeof(kChecks) / sizeof(kChecks[0]);

}  // namespace cs3370_test_detail

// =====================================================================
// The one function you call.
//   runRequiredChecks()          -- all checks
//   runRequiredChecks({2, 9})    -- only the checks listed
// Returns the number of failed checks.
// =====================================================================
inline int runRequiredChecks(std::initializer_list<int> which = {}) {
    namespace d = cs3370_test_detail;

    std::set<int> selected;
    for (int n : which) {
        if (n < 1 || n > d::kNumChecks)
            std::cout << "(ignoring unknown check number " << n
                      << "; valid checks are 1-" << d::kNumChecks << ")\n";
        else
            selected.insert(n);
    }
    if (which.size() == 0)
        for (int n = 1; n <= d::kNumChecks; ++n) selected.insert(n);

    // Save the stream's formatting so your later output is not affected.
    const std::ios_base::fmtflags oldFlags = std::cout.flags();

    std::cout << "\nCS 3370 Program 3 -- BigInt required checks\n";
    d::Reporter report;
    for (int n : selected) {
        try {
            d::kChecks[n - 1](report);
        } catch (const std::exception& e) {
            report(std::to_string(n), "unexpected exception", false,
                   "no exception", e.what());
        } catch (...) {
            report(std::to_string(n), "unexpected exception", false,
                   "no exception", "a non-standard exception");
        }
        std::cout.flush();   // keep the output if a later check crashes
    }

    std::cout << "\n=====================================\n"
              << "  " << report.passed << " passed, " << report.failed << " failed\n"
              << "=====================================\n";
    std::cout.flags(oldFlags);
    return report.failed;
}

#endif  // CS3370_TEST_BIGINT_H
